[package]
name = "rust-deploy"
version = "0.1.0"
authors = ["Ben Pinhorn <00ben.allen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ftp = "3.0.1"
clap = "2.33.0"
dotenv = "0.14.1"
